I'm sorry, but an uncaught exception occurred.

Executing ATL code at game/script.rpy:445
  File "game/script.rpy", line 404, in script
    show edog:
Exception: ATL appears to be in an infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 404, in script
    show edog:
  File "C:\Users\singi\Documents\renpy-7.3.5-sdk\renpy\ast.py", line 1183, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\singi\Documents\renpy-7.3.5-sdk\renpy\ast.py", line 1153, in show_imspec
    atl=atl)
  File "C:\Users\singi\Documents\renpy-7.3.5-sdk\renpy\exports.py", line 717, in show
    sls.add(layer, img, key, zorder, behind, at_list=at_list, name=name, atl=atl, default_transform=default_transform, transient=transient)
  File "C:\Users\singi\Documents\renpy-7.3.5-sdk\renpy\display\core.py", line 1078, in add
    thing._show()
  File "C:\Users\singi\Documents\renpy-7.3.5-sdk\renpy\display\transform.py", line 1048, in _show
    super(ATLTransform, self)._show()
  File "C:\Users\singi\Documents\renpy-7.3.5-sdk\renpy\display\transform.py", line 1014, in _show
    self.update_state()
  File "C:\Users\singi\Documents\renpy-7.3.5-sdk\renpy\display\transform.py", line 1036, in update_state
    fr = self.execute(self, self.st, self.at)
  File "C:\Users\singi\Documents\renpy-7.3.5-sdk\renpy\atl.py", line 564, in execute
    action, arg, pause = block.execute(trans, timebase, self.atl_state, events)
  File "C:\Users\singi\Documents\renpy-7.3.5-sdk\renpy\atl.py", line 799, in execute
    raise Exception("ATL appears to be in an infinite loop.")
Exception: ATL appears to be in an infinite loop.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
AE Party 1.0
Tue Aug 25 15:58:56 2020
